### ISSUE TITLE
Walkthrough - npm start does not work as router is not defined

### ISSUE THREAD

**Issue by joeylouise** [foundersandcoders/tdd-node-server-with-shot-and-tape#20]
@njsfield At the beginning of the walkthrough, we say to run `npm start` to check that everything is working ok, but this doesn't work because `router` is not defined.

Does it make sense to remove `router` from the server setup below?
 
```
http.createServer(router).listen(port, () => {
  console.log(`Server running at port http://${hostname}:${port}`)
});
```

**Comment by eliascodes** [comment]
closed by #24
