### ISSUE TITLE
Exercise 2: we can't figure out how router.js and test.js would help

### ISSUE THREAD

**Issue by joeylouise** [foundersandcoders/tdd-node-server-with-shot-and-tape#23]
@njsfield 

Exercise 2 says the following, but we can't figure out how router.js and test.js would help:

A new route at '/blog'; if the request method is get, respond with a status code of 200, and a JSON object containing an array of three strings... (If you get stuck on how to start, have a look at router.js and test.js in this repo)

**Comment by njsfield** [comment]
Apologies- several of these issues were related to some last minute PR changes that were not fully tested. 

To clarify, I'm the original author but am not maintaining this repo so am unassigning to ensure progress isn't halted!

**Comment by joeylouise** [comment]
Ok cool, thanks @njsfield, we won't assign you to the issues 👍  Do you have any solutions to the exercises?

**Comment by joeylouise** [comment]
We have pushed a solutions branch, so I'm closing this issue
