### ISSUE TITLE
confusing use of .listen method of http 

### ISSUE THREAD

**Issue by y-zaky** [foundersandcoders/tdd-node-server-with-shot-and-tape#29]
const http = require('http');
const hostname = process.env.HOSTNAME || 'localhost';
const port = process.env.PORT || 4000;

http.createServer().listen(port, hostname, () => {
  console.log(`Server running at port http://${hostname}:${port}`)
});

This is the first workshop of the week (Hot and Tape testing). However, in the previous week students used .listen in this format : server.listen(path[, callback])

However, in this workshop they are expected to immediately understand what is happening with this format : 
server.listen([port][, hostname][, backlog][, callback])

This might be confusing... shall I change this ?

**Comment by paulhanna1933** [comment]
@finnhodgkin would you consider this an issue?

**Comment by finnhodgkin** [comment]
I'm not fussed either way. I would hope that students could translate the change themselves, and if not that it's a good chance for them to do some documentation Googling.

Totally up to you though @y-zaky
