### ISSUE TITLE
different routes exercises 

### ISSUE THREAD

**Issue by Qamar-93** [foundersandcoders/tdd-node-server-with-shot-and-tape#30]
- More explanation of how to use the payload in request.
We can also add the exercises like:   
- Respond with a status code of 500, for any internal error. 
- For routes with the values like ('/blog/:user'), respond with 200 and a message with ('user blog')

**Comment by finnhodgkin** [comment]
@Qamar-93 Feel free to make the changes whenever you can, just assign me in a PR when you're done.
